// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdinXSiteMVC2.Data;

namespace OdinXSiteMVC2.Migrations.OdinXSiteMVC2
{
    [DbContext(typeof(OdinXSiteMVC2Context))]
    [Migration("20220111030433_ini")]
    partial class ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("OdinXSiteMVC2.Models.Exec", b =>
                {
                    b.Property<int>("execID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("execFirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("execGamingTag")
                        .HasColumnType("longtext");

                    b.Property<string>("execHierarchy")
                        .HasColumnType("longtext");

                    b.Property<string>("execLastName")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("execPic")
                        .HasColumnType("longblob");

                    b.Property<string>("execTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("favGame")
                        .HasColumnType("longtext");

                    b.Property<int?>("loginAmt")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.HasKey("execID");

                    b.ToTable("Exec");

                    b.HasData(
                        new
                        {
                            execID = 1,
                            execFirstName = "Dammy",
                            execGamingTag = "Gobljnn",
                            execHierarchy = "Founding",
                            execLastName = "Adebayo",
                            execTitle = "Programmer",
                            favGame = "OW",
                            username = "Gobljnn"
                        },
                        new
                        {
                            execID = 2,
                            execFirstName = "Kitan",
                            execGamingTag = "Kitan3000",
                            execHierarchy = "Founding",
                            execLastName = "Adebowale",
                            execTitle = "Photographer",
                            favGame = "COD",
                            username = "Kitan3000"
                        },
                        new
                        {
                            execID = 3,
                            execFirstName = "Nathan",
                            execGamingTag = "Fishboy8383",
                            execHierarchy = "Founding",
                            execLastName = "Stayer",
                            execTitle = "Community Manager",
                            favGame = "League",
                            username = "Fishboy8383"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
