// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdinXSiteMVC2.Data;

namespace OdinXSiteMVC2.Migrations.OdinXSiteMVC2
{
    [DbContext(typeof(OdinXSiteMVC2Context))]
    [Migration("20220118175930_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("OdinXSiteMVC2.Models.DTO.NewRegDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext");

                    b.Property<string>("gamerTag")
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .HasColumnType("longtext");

                    b.Property<string>("profilePic")
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.Property<string>("roleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("NewReg");
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.Exec", b =>
                {
                    b.Property<string>("execID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bio")
                        .HasColumnType("longtext");

                    b.Property<string>("execFirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("execGamingTag")
                        .HasColumnType("longtext");

                    b.Property<string>("execHierarchy")
                        .HasColumnType("longtext");

                    b.Property<string>("execLastName")
                        .HasColumnType("longtext");

                    b.Property<string>("execPic")
                        .HasColumnType("longtext");

                    b.Property<string>("execTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("favGame")
                        .HasColumnType("longtext");

                    b.Property<int?>("loginAmt")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.HasKey("execID");

                    b.ToTable("Exec");

                    b.HasData(
                        new
                        {
                            execID = "001",
                            bio = " Oluwadamilola Gobljnn Adebayo (Dammy), a chemical engineer, one of the co-founders of ODINxGAMING goes by the gamer His favourite genre to play is FPS, which includes a shit - ton of Overwatch and Call of Duty.He also dabbles in a bit of Rocket League buthe dog water.Gobljnn is ODINxGaming's Lead Developer and UI Support member.",
                            execFirstName = "Dammy",
                            execGamingTag = "Gobljnn",
                            execHierarchy = "Founding",
                            execLastName = "Adebayo",
                            execTitle = "Programmer",
                            favGame = "OW",
                            username = "Gobljnn"
                        },
                        new
                        {
                            execID = "002",
                            execFirstName = "Kitan",
                            execGamingTag = "Kitan3000",
                            execHierarchy = "Founding",
                            execLastName = "Adebowale",
                            execTitle = "Photographer",
                            favGame = "COD",
                            username = "Kitan3000"
                        },
                        new
                        {
                            execID = "003",
                            execFirstName = "Nathan",
                            execGamingTag = "Fishboy8383",
                            execHierarchy = "Founding",
                            execLastName = "Stayer",
                            execTitle = "Community Manager",
                            favGame = "League",
                            username = "Fishboy8383"
                        });
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.Roles.Role", b =>
                {
                    b.Property<string>("roleID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("roleName")
                        .HasColumnType("longtext");

                    b.HasKey("roleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.Socials.ExecSocial", b =>
                {
                    b.Property<int>("socialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("discordLink")
                        .HasColumnType("longtext");

                    b.Property<string>("discordName")
                        .HasColumnType("longtext");

                    b.Property<string>("execId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("execName")
                        .HasColumnType("longtext");

                    b.Property<string>("instaLink")
                        .HasColumnType("longtext");

                    b.Property<string>("live")
                        .HasColumnType("longtext");

                    b.Property<string>("scLink")
                        .HasColumnType("longtext");

                    b.Property<string>("tiktokLink")
                        .HasColumnType("longtext");

                    b.Property<string>("ttvlink")
                        .HasColumnType("longtext");

                    b.Property<string>("twitLink")
                        .HasColumnType("longtext");

                    b.HasKey("socialID");

                    b.HasIndex("execId");

                    b.ToTable("ExecSocial");
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("imageName")
                        .HasColumnType("longtext");

                    b.Property<string>("imagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("userID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("userID");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.DTO.NewRegDTO", b =>
                {
                    b.HasOne("OdinXSiteMVC2.Models.Roles.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("roleId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.Socials.ExecSocial", b =>
                {
                    b.HasOne("OdinXSiteMVC2.Models.Exec", "Users")
                        .WithMany()
                        .HasForeignKey("execId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OdinXSiteMVC2.Models.UserImage", b =>
                {
                    b.HasOne("OdinXSiteMVC2.Models.DTO.NewRegDTO", "Users")
                        .WithMany()
                        .HasForeignKey("userID");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
